# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0443', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='point',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 4, 21, 4, 11, 491571), verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c'),
        ),
    ]
